# Generated by Django 3.1.5 on 2021-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('python', 'P'), ('django', 'D'), ('javascript', 'J'), ('react', 'R'), ('other', 'O')], max_length=50),
        ),
    ]
