# Generated by Django 3.1.5 on 2021-03-04 19:28

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210303_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
