# Generated by Django 3.1.5 on 2021-03-04 19:41

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210304_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hello',
            field=django_quill.fields.QuillField(default='hey'),
            preserve_default=False,
        ),
    ]
