# Generated by Django 3.1.5 on 2021-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210305_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
        migrations.AddField(
            model_name='blog',
            name='text_test_1',
            field=models.TextField(null=True),
        ),
    ]
