# Generated by Django 3.1.5 on 2021-04-01 15:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210401_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text_test_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
