# Generated by Django 3.1.5 on 2021-04-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blog_text_test_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='text_test_2',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='text_test_1',
        ),
    ]
